import { NextRequest } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(req: NextRequest) {
    // Parse incoming request body
    const {
        name,
        email,
        phone,
        city,
        message,
        service,
        vehicle,
        product,
        volume,
        fromLocation,
        toLocation,
        estimateFrom,
        estimateTo
    } = await req.json();

    // Set up transporter for sending email
    const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: process.env.EMAIL_USER,
            pass: process.env.EMAIL_PASSWORD,
        },
    });

    const mailOptions = {
        from: process.env.EMAIL_USER,
        to: process.env.COMPANY_EMAIL,
        subject: 'New Request Quote from Your Website',
        html: `
        <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
            <h2 style="color: #4CAF50; text-align: center;">New Request for Quote</h2>
            <p style="font-size: 1.1em; margin-bottom: 20px;">You have received a new request for a quote from your website. Here are the details:</p>
            
            <div style="background-color: #f9f9f9; padding: 15px; border-radius: 6px; margin-bottom: 20px;">
                <p><strong>Name:</strong> ${name}</p>
                <p><strong>Email:</strong> <a href="mailto:${email}" style="color: #4CAF50; text-decoration: none;">${email}</a></p>
                <p><strong>Phone:</strong> <a href="tel:${phone}" style="color: #4CAF50; text-decoration: none;">${phone}</a></p>
                <p><strong>City:</strong> ${city}</p>
            </div>

            <h3 style="color: #4CAF50; margin-bottom: 10px;">Request Details:</h3>
            <div style="background-color: #f9f9f9; padding: 15px; border-radius: 6px; margin-bottom: 20px;">
                <p><strong>Service Type:</strong> ${service}</p>
                <p><strong>Vehicle:</strong> ${vehicle}</p>
                <p><strong>Product Category/Industry:</strong> ${product}</p>
                <p><strong>Volume:</strong> ${volume}</p>
            </div>

            <h3 style="color: #4CAF50; margin-bottom: 10px;">Locations & Dates:</h3>
            <div style="background-color: #f9f9f9; padding: 15px; border-radius: 6px; margin-bottom: 20px;">
                <p><strong>From Location:</strong> ${fromLocation}</p>
                <p><strong>To Location:</strong> ${toLocation}</p>
                <p><strong>Estimate From:</strong> ${estimateFrom}</p>
                <p><strong>Estimate To:</strong> ${estimateTo}</p>
            </div>

            <h3 style="color: #856404;">Message:</h3>
            <div style="background-color: #fff3cd; padding: 15px; border: 1px solid #ffeeba; border-radius: 6px;">
                <p>${message}</p>
            </div>

            <p style="text-align: center; margin-top: 30px;">
                <small style="color: #777;">This email was generated by your website’s Request Quote form.</small>
            </p>
        </div>
        `,
    };

    try {
        // Send email
        await transporter.sendMail(mailOptions);
        return new Response(JSON.stringify({ message: 'Request for quote sent successfully!' }), { status: 200 });
    } catch (error) {
        console.error('Error sending email:', error);
        return new Response(JSON.stringify({ message: 'Failed to send request for quote. Please try again later.' }), { status: 500 });
    }
}
